### ISSUE TITLE
Can you provide more help on using this plugin?

### ISSUE THREAD

**Issue by Tigerstrength** [geertmeersman/aiorobonect#5]
Hi @geertmeersman, 

Love the work you are doing here. I was looking for quite some time for a plug-in / library / helper to use Robonect with my existing Domoticz setup. Because there is no native support I want to write a very basic python script to just upload the status to domoticz and start and stop the lawnmower.

However I am find myself struggling how to get this Python library to work. Normally I run pip <libraryname> and I after that I can import the library in my script. How do i do this with your code? And where can I find an overview of the available commands and their arguments?

Maybe you can add this info to the readme part? Thanks in advance!

**Comment by geertmeersman** [comment]
Hi, it's still a work in progress 😀
I am writing a rest and mqtt integration for Home Assistant and I wrote this library for the API part.
But I'll document it soon!

**Comment by Tigerstrength** [comment]
That is great to hear! If you want to then maybe you can use MQTT Autodiscovery? That is fully supported by both Domoticz and HA. The devices will automatically being added when subscribing to the mqtt topic. Works quit brilliant 😃 Thanks for your work so far!

**Comment by geertmeersman** [comment]
MQTT Auto discovery is already built in in my HA integration :-)

**Comment by geertmeersman** [comment]
![image](https://github.com/geertmeersman/aiorobonect/assets/1844091/a3d66632-3c20-4032-87e1-34dbc3a11bb2)
